# Invoked via: /git:review

description = "Review 暂存的更改"
prompt = """
## 任务：全面审查暂存的更改

**深入代码审查**：
 * **你的主要职责是对暂存的更改中引入的变更进行彻底且深入的代码审查**。请将你的分析重点放在以下标准上：
 * **正确性**：代码是否能够实现其声明的目的，没有bug或逻辑错误？
 * **可维护性**：代码是否干净、结构良好，并且易于未来理解和修改？考虑因素包括代码清晰度、模块化以及遵循既定的设计模式。
 * **可读性**：代码是否有必要的注释，并且格式始终符合我们项目的编码风格指南？
 * **效率**：变更是否引入了明显的性能瓶颈或资源浪费？
 * **安全性**：是否存在潜在的安全漏洞或不安全的编码实践？
 * **边界情况和错误处理**：代码是否适当处理了边界情况和潜在错误？
 * **可测试性**：新代码或修改后的代码是否得到了充分的测试（即使预检通过）？建议补充哪些测试用例可以改进覆盖率或健壮性。
 * 根据你的分析，你将确定暂存的更改是否能够作为Pr提交。

"""